<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/admin/dashboard">Simple Skeleton CMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="/admin/dashboard"><i class="fas fa-home"></i> Dashboard</a></li>
            <li class="nav-item"><a class="nav-link" href="/admin/pages"><i class="far fa-file"></i> Pagine</a></li>
            <li class="nav-item"><a class="nav-link" href="/admin/blocks"><i class="fas fa-th-large"></i> Layout dei blocchi</a></li>
            <li class="nav-item"><a class="nav-link" href="/admin/articles"><i class="far fa-calendar-alt"></i> Articoli</a></li>
            <li class="nav-item"><a class="nav-link" href="/admin/categories"><i class="fas fa-coffee"></i> Categorie</a></li>
        </ul>
        <ul class="list-inline navbar-text">
            <li class="list-inline-item">Bentornato, <a href="/admin/profile"><?php echo $this->e($this->getUser()->getUsername()); ?></a></li>
            <li class="list-inline-item"><a href="/admin/settings"><i class="fas fa-cog"></i></li>
            <li class="list-inline-item"><a href="/admin/logout" class="text-danger"><i class="fas fa-power-off"></i></a></li>
        </ul>
    </div>
</nav>