<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/admin/dashboard">Simple Skeleton CMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="/admin/dashboard"><i class="fas fa-home"></i> Dashboard</a></li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                    <?php echo strtoupper($this->e($this->getUser()['username'])); ?>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="/" target="_blank">Anteprima del sito</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/admin/logout" onclick="return confirm('Sei sicuro di voler uscire?')">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
