<?php $this->layout('admin::layout', []); ?>
<?php $this->insert('admin::partials/navbar'); ?>
<section class="container-fluid mt-5">
    <div class="card">
        <h5 class="card-header">Articoli</h5>
        <div class="card-body">
            <ul class="nav nav-tabs">
                <li class="nav-item"><a class="nav-link active" href="#">Visualizza contenuti</a></li>
                <li class="nav-item"><a class="nav-link" href="#"><i class="fas fa-plus"></i> Aggiungi nuovo</a></li>
            </ul>
            <br>
            <table class="js-datatable table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Articolo</th>
                    <th>Categoria</th>
                    <th>Dal</th>
                    <th>Al</th>
                    <th>Home</th>
                    <th>Pubblicazione</th>
                    <th>Modifica</th>
                    <th>Operazioni</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Lorem ipsum</td>
                    <td>Lorem ipsum</td>
                    <td>Lorem ipsum</td>
                    <td>Lorem ipsum</td>
                    <td>Lorem ipsum</td>
                    <td>Lorem ipsum</td>
                    <td>Lorem ipsum</td>
                    <td>Lorem ipsum</td>
                    <td>
                        <div class="btn-group btn-group-sm" role="group">
                            <button type="button" class="btn btn-primary"><i class="fas fa-edit"></i></button>
                            <button type="button" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</section>