<?php $this->layout('admin::layout', []); ?>
<?php $this->insert('admin::partials/navbar'); ?>
<section class="mt-3">
    <h1>Dashboard</h1>
    <div class="card">
        <div class="card-body">
            <p>Bentornato <?php echo $this->e($this->getUser()['username']); ?>, Il tuo ultimo login è stato <?php echo $this->e($this->getDateFromTimestamp($this->getUser()['last_login'])); ?></p>
        </div>
    </div>
</section>