<?php $this->layout('admin::layout', []); ?>
<section class="mt-5">
    <div class="card w-25 m-auto">
        <div class="card-header">Simple Skeleton CMS</div>
        <div class="card-body">
            <?php echo $this->getAlertMessages(); ?>
            <form action="" class="js-validate" method="post" enctype="application/x-www-form-urlencoded">
                <div class="form-group">
                    <label for="usermail">Indirizzo email</label>
                    <input type="email" class="form-control" id="usermail" name="usermail" value="" required>
                </div>
                <div class="form-group">
                    <label for="pwd">Password</label>
                    <input type="password" class="form-control" id="pwd" name="pwd" value="" required>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" class="form-check-input" id="remember" name="remember" value="1">
                    <label class="form-check-label" for="remember">Rimani collegato</label>
                </div>
                <input type="hidden" name="token" value="<?php echo $this->e($token); ?>">
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</section>