<?php $this->layout('admin::layout', []); ?>
<?php $this->insert('admin::partials/navbar'); ?>
<section class="mt-3">
    <h1>Aggiungi nuova pagina</h1>
    <form action="" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs">
                            <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#italiano">Italiano</a></li>
                            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#english">English</a></li>
                            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#deutsch">Deutsch</a></li>
                            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#francais">Français</a></li>
                            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#Espanol">Español</a></li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="italiano" role="tabpanel" aria-labelledby="home-tab">
                                <div class="form-group">
                                    <label for="title_it">Email address</label>
                                    <input type="text" class="form-control" name="title_it" id="title_it" value="">
                                </div>
                                <div class="">
                                    <ul class="nav nav-pills justify-content-center">
                                        <li class="nav-item"><a class="nav-link active" data-toggle="pill" href="#pill_content_1_it">Contenuto</a></li>
                                        <li class="nav-item"><a class="nav-link" data-toggle="pill" href="#pill_content_2_it">Contenuto secondario</a></li>
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane fade show active" id="pill_content_1_it">
                                            <div class="form-group">
                                                <label for="content_1_en"></label>
                                                <textarea class="form-control" name="content_1_en" id="content_1_en"></textarea>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="pill_content_2_it">
                                            <div class="form-group">
                                                <label for="content_2_en"></label>
                                                <textarea class="form-control" name="content_2_en" id="content_2_en"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="english" role="tabpanel" aria-labelledby="profile-tab">e</div>
                            <div class="tab-pane fade" id="deutsch" role="tabpanel" aria-labelledby="profile-tab">d</div>
                            <div class="tab-pane fade" id="francais" role="tabpanel" aria-labelledby="profile-tab">f</div>
                            <div class="tab-pane fade" id="Espanol" role="tabpanel" aria-labelledby="profile-tab">es</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card bg-light">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="parent">parent</label>
                            <select class="form-control" name="parent" id="parent">
                                <option value="">---</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>

                    </div>
                </div>
            </div>
        </div>
    </form>
</section>


